[package]
name = "async_http_get_spawn_local"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Use 'unstsable' feature for 'spawn_local'.
async-std = { version = "*", features = ["unstable"] }
